### ISSUE TITLE
Medo crashes on launch (32bit)

### ISSUE THREAD

**Issue by Begasus** [smallstepforman/Medo#9] opened 2020-12-24 09:39 UTC
Updated the work @pulkomandy did on recipe at haikuports at https://github.com/haikuports/haikuports/pull/5509
The build and install is working fine, but the app crashes on launch (will add a debug report later for this)

**Comment by smallstepforman** [comment] 2020-12-31 02:36
Hi Begasus.  Thank you for reporting this issue.  I believe that the issue is with the way the application was built / linked, since the 32 bit version I created and uploaded to Haiku forums did not exhibit this problem (it ran OK during my brief test).
Sadly, none of the PC's I have access to are able to boot Haiku 32 bit (interestingly, they all work fine with 64 bit version of Haiku).  The 32 bit build I created was from a friends PC, and you can understand my hesitation to support a build which I am unable to do regression tests on.  I ran out of time investigating why a 32 bit hpkg file could not install properly, but unzipping the hpkg seems to allow running a 32 bit version of the app.

I have applied the patches necessary to build the application in a 32 bit environment.  Please use the recommended "create_package" script to compile the 32 bit version.

I will close this issue since the supplied binary does not crash on launch (32 bit).  Thanks again.

**Closed as completed by smallstepforman** 2020-12-31 02:36 UTC

**Comment by Begasus** [comment] 2020-12-31 05:56
@smallstepforman Thanks for looking into this, I'll try to see that we can update our (disabled) recipe for now at haikuports, sorry for not getting back to you on this one, I also checked the zip and it crashed (on quit now) also here (thought it was ok last time I checked), didn't have time to update here. :+1: 
**EDIT** This is on R1/Beta2 hrev54154+123, maybe nightly doesn't suffer from this, last check also crashed (from commit https://github.com/smallstepforman/Medo/commit/ef2531e746c3c80ce4bc9480ecf216139a951ec5)
Latest commit (https://github.com/smallstepforman/Medo/commit/2f27322fe8a511716ac5730dffba4aeecffca847) checkout fails to build (think commit https://github.com/smallstepforman/Medo/commit/07ca7743ad4d2ed3a878fc0f41e321344798734c is involved here, I'm not a developer, so can only report :) ): https://paste.ubuntu.com/p/QJVk7VkMBB/
