### ISSUE TITLE
Clip splitting is inaccurate

### ISSUE THREAD

**Issue by parnikkapore** [smallstepforman/Medo#13] opened 2020-12-27 03:11 UTC
When I try to split a clip, it is highly likely to split a few seconds to either side of the playhead.

Or maybe it actually splits at the position you right-clicked - I haven't investigated.

**Comment by MarcoRavich** [comment] 2020-12-28 07:43
@smallstepforman LosslessCut may help to fix the issue:
https://github.com/mifi/lossless-cut

**Comment by smallstepforman** [comment] 2020-12-31 01:10
Hi parnikkapore.  Split point is at right mouse down BPoint (or ctrl-left click).  Also, if you hold shift when resizing clip, it will move adjacent clip as well.  I was thinking to add a special "magnify" split feature, which allows the user to magnify the split point for R2.  For R1, I will close this issue since it works as designed. 

forart, all editing is non destructive (lossless).

Thank you both for taking the time to post feedback.

**Closed as completed by smallstepforman** 2020-12-31 01:10 UTC
