### ISSUE TITLE
Chain in export window draws weirdly the first time

### ISSUE THREAD

**Issue by parnikkapore** [smallstepforman/Medo#12] opened 2020-12-27 03:09 UTC
![See this image](https://user-images.githubusercontent.com/9170353/103163070-7e9dda80-482b-11eb-9016-1ac4bc03e3ef.png)

It fixes itself if I click it or drag another window over it.

**Comment by smallstepforman** [comment] 2020-12-31 01:14
Hi parnikkapore.  Yes, there are a few BView redraw clitches which are due to the AppServer algorithm to determine which BView's are dirty and require a redraw.  This works well when the BViews are not overlapped, but when they're overlapped glitches like this happen.  Its not an easy fix since I do not want the performance penalty to redraw everything.  It works when well when the window has focus (no glitches then), but for background windows the dirty notification is problematic.  I will try to fix this before R1 is released.  Thank you for posting feedack.

I will close this issue since its a duplicate of another redraw glitch.  I'm sure many more will be reported, and they all have the same root cause.

Thanks again.

**Closed as completed by smallstepforman** 2020-12-31 01:14 UTC
