### ISSUE TITLE
Instability with music files with album art

### ISSUE THREAD

**Issue by parnikkapore** [smallstepforman/Medo#10] opened 2020-12-27 03:04 UTC
Medo seems to behave really weirdly when dealing with music files that have album art. For example, on nightly Haiku, it has both a video track and an audio track, but the video track points to some corrupt-looking garbage (uninitialized buffer?).

This might be caused by false assumptions on whether different parts of the API report that the file has a video track or not.

My test file also crashed Medo once rendering finishes. [Traceback](https://github.com/smallstepforman/Medo/files/5744047/Medo-1784-debug-26-12-2020-10-16-08.report.txt)

**Comment by smallstepforman** [comment] 2020-12-31 02:30
Hi parnikkapore, I'm unable to reproduce the issue.  I used lame --ti pic.jpg some.mp3 to create an mp3 with album art, and it processed fine on a Haiku nightly.  A couple of months ago there were BMediaTrack issues with embedded art which were resolved in a nightly update.  May this be the problem you encountered?

Since it seems to work on nightly, I will close this issue.

**Closed as completed by smallstepforman** 2020-12-31 02:30 UTC
